# -*- coding: utf-8 -*-
"""online_Reatail

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/embedded/projects/online-retail-500421/locations/us-central1/repositories/9223e427-7d0a-4e00-92e8-2436b1ae6b4c
"""

import pandas as pd
import matplotlib .pyplot as plt
import seaborn as sns

import pandas as pd
import matplotlib .pyplot as plt
import seaborn as sns

"""Step 1: Download and Save the File Locally"""

!gsutil cp gs://online_retail01/online_retail.csv ./online_retail01.csv

# The file signature 'PK' suggests this might be an Excel (.xlsx) file despite the .csv extension.
# Let's try reading it with pd.read_excel.
# Note: You might need to install 'openpyxl' if it's not present: !pip install openpyxl
try:
    df = pd.read_excel("online_retail01.csv")
    print("File successfully read as an Excel file.")
    print(df.head())
except Exception as e:
    print(f"Excel read failed: {e}")
    # Fallback: if it's actually a CSV with bad lines, use engine='python' and on_bad_lines='skip'
    df = pd.read_csv("online_retail01.csv", encoding="ISO-8859-1", on_bad_lines="skip", engine="python")
    print("File read as CSV by skipping bad lines.")
    print(df.head())

import pandas as pd

# Switching 'engine' to 'python' allows more forgiving parsing
df = pd.read_csv("online_retail01.csv", encoding="ISO-8859-1", engine="python", on_bad_lines="skip")

print("Data loaded successfully with Python engine!")
print(df.head())

"""Step 2: Read the File into Pandas"""

import pandas as pd
df = pd.read_excel("online_retail01.csv")
df.head()

df.shape

df.info()

df.isnull().sum()

"""Step- 2 (data Preprocessing) [Handling the missing value:--]"""

df.head()

# (1.) Handling the missing value:

# Create a mapping of StockCode to Description from non-null values
desc_lookup = (
    df[df["Description"].notna()]
    .groupby("StockCode")["Description"]
    .agg(lambda x: x.mode()[0])
)
# Fill missing descriptions based on the StockCode mapping
df["Description"] = df["Description"].fillna(df["StockCode"].map(desc_lookup))

# drop StockCodes with no description anywhere
df = df.dropna(subset=["Description"])

df["Description"].isnull().sum()

df["Description"].head

df = df.dropna(subset=["Description"])

# CustomerID nulls can't be filled -> drop
df = df.dropna(subset=["CustomerID"])

df["CustomerID"].isnull().sum()

df["CustomerID"], df["Description"].head

df.isnull().sum()

"""Feature Enginerring"""

df.columns

# Remove cancelled invoices + bad quantity/price
df = df[~df["InvoiceNo"].astype(str).str.startswith("C")]
df = df[(df["Quantity"] > 0) & (df["UnitPrice"] > 0)]

df["TotalAmount"] = df["Quantity"] * df["UnitPrice"]
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"], dayfirst=True)

reference_date = df["InvoiceDate"].max()

df["Invoice_tenure_days"] = (reference_date - df["InvoiceDate"]).dt.days

df = df.drop(columns=["Invoice_tenure_days"])

df.info

df_cleaned = df

df_cleaned.shape

"""Feature Enginerring"""

df_cleaned.info

df_cleaned.head()

df_cleaned.columns

"""Detecting the Outliers:-"""

# Remov the Outliers

"""Exploratoty Data Analysis"""

print("Top country by invoices:")
df.groupby("Country")["InvoiceNo"].nunique().sort_values(ascending=False).head(5)

print("top Selling Product:-")
df.groupby("Description")["Quantity"].sum().sort_values(ascending=False).head(5)

# First line calculates the sum per country
country_sums = df.groupby("Country")["Quantity"].sum().sort_values(ascending=False)
print(country_sums.head())
df.head()

"""step 4. RFM Feature Table = one row per customer, with three calculated columns that summarize their buying behavior.(Customer Purchase behaviour):--"""

# Recency , Frequency, Monetry
# Low recency → engaged right now
# High frequency → loyal repeat buyer
# High monetary → valuable to the business

# Calculate TotalAmount first
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']

max_date = df["InvoiceDate"].max()

rfm = df.groupby("CustomerID").agg(
    recency=("InvoiceDate", lambda x: (max_date - x.max()).days),
    frequency=("InvoiceNo", "nunique"),
    monetary=("TotalAmount", "sum")
).reset_index()

print(type(rfm))

"""5 — Standardize RFM values"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[["recency", "frequency", "monetary"]])

sample_df = df_cleaned[["Quantity", "UnitPrice"]].sample(2000, random_state=42)
sns.pairplot(sample_df)
plt.show()

# Rebuild the RFM table if needed
max_date = df["InvoiceDate"].max()

rfm = df.groupby("CustomerID").agg(
    recency=("InvoiceDate", lambda x: (max_date - x.max()).days),
    frequency=("InvoiceNo", "nunique"),
    monetary=("TotalAmount", "sum")
).reset_index()

print(type(rfm))   # should now say DataFrame

# Use a different variable name for the column list
rfm_cols = ["recency", "frequency", "monetary"]
sns.pairplot(rfm[rfm_cols])
plt.show()

"""Remove  the outlier:--( in Monetoty and frequency):--"""

print("Before outlier removal:", rfm.shape)

def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

rfm_clean = rfm.copy()
for col in ["recency", "frequency", "monetary"]:
    rfm_clean = remove_outliers_iqr(rfm_clean, col)

print("After outlier removal:", rfm_clean.shape)

rfm = rfm_clean.reset_index(drop=True)

sns.pairplot(rfm[["recency", "frequency", "monetary"]])
plt.show()

"""HeatMap"""

corr = rfm.corr(numeric_only=True)
print(corr)

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(5, 4))

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm")
plt.title("RFM Correlation Heatmap")
plt.show()

"""Feature encoding and Scaling Our Data"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
rfm_scaled = scaler.fit_transform(rfm[["recency", "frequency", "monetary"]])

rfm_scaled

"""Visualize Our data"""

rfm_scaled.shape

from sklearn.decomposition import PCA

# PCA ( in 2D- Dimension)
pca = PCA(n_components=2)

# Using 'rfm_scaled' as defined in the previous scaling step
x_pca = pca.fit_transform(rfm_scaled)

# plot
plt.scatter(x_pca[:, 0], x_pca[:, 1])
plt.xlabel('PCA 1')
plt.ylabel('PCA 2')
plt.title('PCA of RFM Segments')
plt.show()

pca.explained_variance_ratio_

from sklearn.decomposition import PCA

# PCA ( in 3D- Dimension)
pca = PCA(n_components=3)

# Using 'rfm_scaled' as defined in the previous scaling step
x_pca = pca.fit_transform(rfm_scaled)

pca.explained_variance_ratio_

# plot for(3-D Dimension)

from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt

fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection="3d")

ax.scatter(x_pca[:, 0], x_pca[:, 1], x_pca[:,2])
# scatter = ax.scatter(
#     rfm["recency"], rfm["frequency"], rfm["monetary"],
#     c=rfm["kmeans_cluster"], cmap="viridis"
# )
ax.set_xlabel("Recency")
ax.set_ylabel("Frequency")
ax.set_zlabel("Monetary")
plt.title("Customer Clusters (RFM)")
plt.show()

"""Analyze k value:--

1. Elbow Method
"""

!pip install kneed
from sklearn.cluster import KMeans
from kneed import KneeLocator
import matplotlib.pyplot as plt

wcss = []
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(rfm_scaled)
    wcss.append(kmeans.inertia_)

# Automatically detect the elbow point
knee = KneeLocator(range(1, 11), wcss, curve="convex", direction="decreasing")
print("Optimal k (elbow):", knee.elbow)

# Plot the elbow curve
plt.figure()
plt.plot(range(1, 11), wcss, marker="o")
plt.xlabel("Number of clusters (k)")
plt.ylabel("WCSS (inertia)")
plt.title("Elbow Method")
plt.show()

"""2. Silhouette Score"""

from sklearn.metrics import silhouette_score
from sklearn.cluster import KMeans

scores = []

for k in range(2, 11):
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = kmeans.fit_predict(rfm_scaled)
    score = silhouette_score(rfm_scaled, labels)
    scores.append(score)

# Best k by silhouette
best_k = list(range(2, 11))[scores.index(max(scores))]
print(f"Best k by silhouette score: {best_k} (score={max(scores):.3f})")

# Plot silhouette scores across k
import matplotlib.pyplot as plt

plt.figure()
plt.plot(range(2, 11), scores, marker="o")
plt.xlabel("Number of clusters (k)")
plt.ylabel("Silhouette Score")
plt.title("Silhouette Score vs k")
plt.show()

import matplotlib.pyplot as plt

k_range = range(2, 11)   # match the range used for silhouette scores

fig, ax1 = plt.subplots(figsize=(8, 6))

# WCSS on left axis (skip k=1 since silhouette starts at k=2)
ax1.plot(k_range, wcss[1:], marker="o", color="blue", label="WCSS")
ax1.set_xlabel("Number of clusters (k)")
ax1.set_ylabel("WCSS (Inertia)", color="blue")
ax1.tick_params(axis="y", labelcolor="blue")

# Silhouette score on right axis
ax2 = ax1.twinx()
ax2.plot(k_range, scores, marker="s", color="red", label="Silhouette Score")
ax2.set_ylabel("Silhouette Score", color="red")
ax2.tick_params(axis="y", labelcolor="red")

plt.title("Elbow (WCSS) + Silhouette Score vs k")
fig.tight_layout()
plt.show()

"""Clusterinf For K=3"""

kmeans_final = KMeans(n_clusters=3, random_state=42, n_init=10)
rfm["kmeans_cluster"] = kmeans_final.fit_predict(rfm_scaled)

# Profile clusters
print(rfm.groupby("kmeans_cluster")[["recency", "frequency", "monetary"]].mean())

# plot
fig = plt.figure(figsize=(8, 6))
ax = fig.add_subplot(111, projection="3d")

scatter = ax.scatter(
    rfm["recency"], rfm["frequency"], rfm["monetary"],
    c=rfm["kmeans_cluster"], cmap="viridis"
)
ax.set_xlabel("Recency")
ax.set_ylabel("Frequency")
ax.set_zlabel("Monetary")
plt.title("Customer Clusters (RFM)")
plt.show()

"""Agglomerative Clustering"""

# Agglomerative clustering:-
from sklearn.cluster import AgglomerativeClustering

from sklearn.cluster import AgglomerativeClustering

agg_clf = AgglomerativeClustering(n_clusters=3, linkage="ward")
labels_agg = agg_clf.fit_predict(rfm_scaled)

rfm["agglo_cluster"] = labels_agg

# Profile agglomerative clusters
print(rfm.groupby("agglo_cluster")[["recency", "frequency", "monetary"]].mean())

"""Plot to compare both algorithms side by side"""

import matplotlib.pyplot as plt

fig, axes = plt.subplots(1, 2, figsize=(14, 6), subplot_kw={"projection": "3d"})

# KMeans plot
axes[0].scatter(rfm["recency"], rfm["frequency"], rfm["monetary"], c=rfm["kmeans_cluster"], cmap="viridis")
axes[0].set_title("KMeans (k=3)")
axes[0].set_xlabel("Recency")
axes[0].set_ylabel("Frequency")


# Agglomerative plot
axes[1].scatter(rfm["recency"], rfm["frequency"], rfm["monetary"], c=rfm["agglo_cluster"], cmap="viridis")
axes[1].set_title("Agglomerative (k=3)")
axes[1].set_xlabel("Recency")
axes[1].set_ylabel("Frequency")
axes[1].set_zlabel("Monetary")

plt.tight_layout()
plt.show()

"""compute silhouette score for Agglomerative to compare numerically:"""

#  1.Compare KMeans vs Agglomerative, pick final model
from sklearn.metrics import silhouette_score
agg_score = silhouette_score(rfm_scaled, labels_agg)
kmeans_score = silhouette_score(rfm_scaled, rfm["kmeans_cluster"])
print(f"KMeans: {kmeans_score:.3f}, Agglomerative: {agg_score:.3f}")

from sklearn.metrics import silhouette_score
agg_score = silhouette_score(rfm_scaled, labels_agg)
print(f"Agglomerative silhouette score: {agg_score:.3f}")

"""Decision: use KMeans as Fian Model:--"""

#  6c. Profile clusters
#  (Label the 3 clusters with business names)
print(rfm.groupby("kmeans_cluster")[["recency", "frequency", "monetary"]].mean())

"""characterization of Clusters:--"""

print(rfm.groupby("kmeans_cluster")[["recency", "frequency", "monetary"]].mean())

# 1. Confirm the problem still exists
print(rfm["kmeans_cluster"].unique())

# 2. Actually retrain KMeans properly (this is the real fix)
from sklearn.cluster import KMeans

kmeans_final = KMeans(n_clusters=3, random_state=42, n_init=10)
rfm["kmeans_cluster"] = kmeans_final.fit_predict(rfm_scaled)

# Confirm it's fixed
print(rfm["kmeans_cluster"].unique())
print(rfm["kmeans_cluster"].dtype)

# 3. Now check cluster profiles
print(rfm.groupby("kmeans_cluster")[["recency", "frequency", "monetary"]].mean())

cluster_map = {
    0: "High-Value",
    1: "Regular",
    2: "At-Risk"
}

rfm["segment_label"] = rfm["kmeans_cluster"].map(cluster_map)

# Confirm before plotting
print(rfm["segment_label"].value_counts())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(6, 4))
sns.countplot(
    x=rfm["segment_label"],
    hue=rfm["segment_label"],
    order=["High-Value", "Regular", "At-Risk"],
    palette="viridis",
    legend=False
)
plt.title("Customer Count per Segment")
plt.xlabel("Segment")
plt.ylabel("Number of Customers")
plt.show()

top_products = df.groupby("Description")["Quantity"].sum().sort_values(ascending=False).head(15).index
subset_sim = sim_df.loc[top_products, top_products]

plt.figure(figsize=(10, 8))
sns.heatmap(subset_sim, cmap="YlOrRd")
plt.title("Product Similarity Heatmap (Top 15 Products)")
plt.xticks(rotation=90)
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()

"""prduct Recommendation"""

custom_palette = {
    "High-Value": "green",
    "Regular": "yellow",
    "At-Risk": "red"
}

plt.figure(figsize=(7, 5))
sns.scatterplot(
    x=rfm["monetary"],
    y=rfm["frequency"],
    hue=rfm["segment_label"],
    palette=custom_palette
)
plt.xlabel("Monetary (Total Spend)")
plt.ylabel("Frequency (Number of Orders)")
plt.title("Customer Segments: Frequency vs Monetary")
plt.show()

sns.countplot(x=rfm["segment_label"], order=["High-Value", "Regular", "At-Risk"])